version: "3.9"

services:
  MM:
    container_name: MM
    image: beginner090902/mediamanagerforaniscraper:latest
    ports:
      - "5002:5000"
    depends_on:
      - Aniworld
  Aniworld:
    container_name: Aniworld
    image: beginner090902/aniworld_scraper_fork:latest
    ports:
      - "5001:5000"
