version: "3.9"

services:
  MM:
    container_name: MM
    image: beginner090902/mediamanagerforaniscraper:latest
    ports:
      - "5002:5000"
    depends_on:
      - Aniworld
    networks:
      - app-network
      
  Aniworld:
    container_name: Aniworld
    image: beginner090902/aniworldscraperfork:latest
    ports:
      - "5001:5000"
    user: "1000:1000"
    volumes:
      - /output:/app/output
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge